import {
  aaveLeverageLong,
  aaveV3SupplyBalanceContinual,
  blockNumberRange,
  chainlinkDataFeed,
  erc20LimitOrder,
  erc20SwapSpotPriceBalanceTokenOut,
  erc20SwapSpotPriceExactTokenIn,
  erc20SwapSpotPriceExactTokenOut,
  erc4626DepositBalanceContinual,
  erc20Transfer,
  ethTip,
  timestampRange,
  uniswapV3HistoricalTwapPercentageChangeIntent,
  uniswapv3TwapIntent,
} from "./modules"

export const intentModulesDefault = [
  aaveLeverageLong,
  aaveV3SupplyBalanceContinual,
  blockNumberRange,
  chainlinkDataFeed,
  ethTip,
  erc20Transfer,
  erc20LimitOrder,
  erc20SwapSpotPriceBalanceTokenOut,
  erc20SwapSpotPriceExactTokenIn,
  erc20SwapSpotPriceExactTokenOut,
  erc4626DepositBalanceContinual,
  timestampRange,
  uniswapV3HistoricalTwapPercentageChangeIntent,
  uniswapv3TwapIntent,
]
